---
- name: install unzip
  apt: name=unzip state=present cache_valid_time=60

- name: get packer
  unarchive:
    src: https://releases.hashicorp.com/packer/0.12.3/packer_0.12.3_linux_amd64.zip
    dest: /usr/local/bin
    remote_src: true
