---
- name: install docker dependencies
  apt: name={{item}} state=present cache_valid_time=60
  with_items:
    - apt-transport-https
    - ca-certificates
    - software-properties-common

- name: add docker apt key
  apt_key: url=https://download.docker.com/linux/ubuntu/gpg state=present

- name: add docker repository
  apt_repository: repo="deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable"

- name: install docker
  apt: name=docker-ce state=present cache_valid_time=60

- name: add user to docker group
  user: name=vagrant groups=docker append=yes
